config/routes.rb
Rails.application.routes.draw do
 
  # 顧客用
# URL /users/sign_in ...
  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
# 管理者用
# URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords],controllers: {
  sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "public/homes#top"
  get '/about' =>'public/homes#about', as: 'about'

  namespace :admin do
    root to: "homes#top"
  end
  namespace :admin do
     resources :clothes, only: [:index, :show, :edit, :create, :update, :destroy]
    
    #get 'clothes/show'
    #get 'clothes/index'
  end

  namespace :admin do
    resources :users, only:[:index, :show, :edit, :update]


  end

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :types, only: [:create, :edit, :update, :destroy, :index]
  end
  #アドミンの
  #検索用
  #問合せ用
  namespace :admin do
    
    get 'procedures/edit'
    get 'procedures/create'
    get 'procedures/update'
  end
  
  namespace :admin do
    get 'materials/edit'
    get 'materials/create'
    get 'materials/update'
  end
  
  #namespace :public do
    #get 'procedures/post'
    #get 'procedures/create'
    #get 'procedures/edit'
  #end

  #namespace :public do
   # get 'materials/post'
    #get 'materials/create'
    #get 'materials/edit'
  #end
  namespace :public do
    resources :comments, only: [:post, :new]
    #get 'comments/post'
    #get 'comments/new'
  end
  namespace :public do
    resources :clothes, only: [:index, :show, :new, :create, :edit, :update, :destroy]
     resources :bookmarks, only: [:create, :destroy, :index]
     resources :materials, only: [:create, :destroy, :update, :post]
     resources :procedure, omly: [:create, :destroy, :update, :post]
       #collection do
        get :bookmarks
       #end
    #get 'clothes/index'
    #get 'clothes/show'
    #get 'clothes/new'
    #get 'clothes/edit'
    #get 'clothes/destroy'
  end

  namespace :public do
   resources :users, only:[:index, :show, :edit, :update]
   get 'users/list' => "uses#list"
  end

  namespace :public do
    resources :inquiries, only:[:new, :create]
  end





end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 # has_many :users, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :clothe

 validates :user_id, uniqueness: { scope: :clothe_id}
 #scopeをつけることで一つのpostに同じuserが重複してlikeできないようにする
end

app/models/clothe.rb
class Clothe < ApplicationRecord

  belongs_to :user#, through: :bookmakes
  belongs_to :genre
  belongs_to :type
  has_many :comments, dependent: :destroy  #Clothe.commentsで、投稿が所有するコメントを取得できる。
  has_many :bookmarks, dependent: :destroy
  has_many :procedures, dependent: :destroy
  has_many :materials, dependent: :destroy

  #関連付けしたモデルを一緒にデータ保存できるようにする
accepts_nested_attributes_for :procedures, :materials, allow_destroy: true



 validates :name, presence: true, length: { maximum: 255 }
 validates :short_text, presence: true, length: { maximum: 65_535 }
 validates :making_time, presence: true, length: { maximum: 30 }
 validates :point, presence: true, length: { maximum: 65_535 }

 has_one_attached :image #ここはファイル名記載


end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user  #Comment.userでコメントの所有者を取得
  belongs_to :clothe  #Comment.clotheでそのコメントがされた投稿を取得

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :clothes

end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/material.rb
class Material < ApplicationRecord
  #一対多のアソシエーション
   belongs_to :clothe
   
   validates :name, presence: true
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  
  #一対多のアソシエーション
belongs_to :clothe
has_one_attached :image #ここはファイル名記載

validates :body, presence: true
validates :image, presence: true

end

app/models/type.rb
class Type < ApplicationRecord

  has_many :clothes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :clothes, dependent: :destroy
  has_many :comments  #User.commentsで、ユーザーの所有するコメントを取得できる。
  has_many :bookmakes, dependent: :destroy
  has_many :bookmakes_clothes, through: :bookmakes, source: :clothe
  has_many :inquiries, dependent: :destroy

 has_one_attached :image #ここはファイル名記載
 #validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
 #validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
 #validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

 #validates :email, uniqueness: true
 #validates :email, presence: true
 #validates :first_name, presence: true
 #validates :last_name, presence: true

 #userオブジェクトのidとpostやlikeオブジェクトのuser_idが同じかどうかを判断
 def mine?(object)
   object.user_id == id
 end

#bookmarkes_clothesテーブルにpostオブジェクトを追加する。
#いいねを押したときに、いいねしたユーザーといいねされた投稿の情報が保存される。
 def bookmakes(post)
   bookmakes_clothes << post
 end

#bookmakes_clothesテーブルから引数のpostオブジェクトに該当するレコードを削除する。
 def unbookmark(post)
   bookmakes_colthes.destroy(post)
 end

#likes_postsテーブルに引数のpostオブジェクトに該当するレコードがあるかを判断する。
 def bookmake?(post)
   bookmakes_clothes.include?(post)
 end

 def full_name
   "#{last_name} #{first_name}"
 end



end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
   @users = User.all
   @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update (user_params)
      #flash[:success] = "User was successfully updated"
    redirect_to admin_user_path
    #else
    #if @item.update(item_params)
     #   redirect_to admin_item_path(@item.id)
    else
    render :edit #, status: :unprocessable_entity
    end
  end

  private
  def user_params
  params.require(:user).permit(:email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :address, :telephone_number, :is_deleted)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
   protected
    def after_sign_in_path_for(resource)
     if user_signed_in?
        root_path#login後遷移path要変更確認用なので
     else
       admin_root_path #login後遷移path確認用なので要変更
     end
    end

  protected

  def configure_permitted_parameters
    
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :telephone_number, :address])
  end

end

app/helpers/admin/clothes_helper.rb
module Admin::ClothesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/inquiries_helper.rb
module Admin::InquiriesHelper
end

app/helpers/admin/materials_helper.rb
module Admin::MaterialsHelper
end

app/helpers/admin/procedures_helper.rb
module Admin::ProceduresHelper
end

app/helpers/admin/types_helper.rb
module Admin::TypesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
   <div class="row">
   <div class style="padding: 50px;">
      <h3 class="border bg-light">

        <div class="mx-3"><%= (@user.last_name + @user.first_name) %>さんの会員情報編集</h3></div>

   </div>
   </div>
 </div>

 <div class="container">
   <div class="row">
       <%= image_tag @user.image.variant(resize: '100x100'), class: 'user-image' if @user.image.attached? %>
  </div>
</div>

<div class="container">
  <div class="row">


     <%= form_with model: [:admin, @user],local: true do |f| %>

       <table width="650px">

       <!--% if @item.errors.any? %>
      <div id="error_explanation">
     <h3>< %= pluralize(@item.errors.count, "error") %> prohibited this book from being saved:</h3>
    <ul>
      < % @item.errors.full_messages.each do |message| %>
        <li>< %= message %></li>
      < % end %>
       </ul>
  </div>
  </div-->

      <tr>
       <th><%= f.label :会員ID %></th>
      <td><%= @user.id %></td>
      </tr>
      <tr>
      <th><%= f.label :氏名 %></th>
      <td><%= f.text_field :first_name, autofocus: true, id:"name",placeholder:"" %>
          <%= f.text_field :last_name, autofocus: true, id:"name",placeholder:"" %></td>
      </tr>
      <tr>
      <th><%= f.label :フリガナ %></th>
      <td><%= f.text_field :first_name_kana, autofocus: true, id:"name",placeholder:"" %>
          <%= f.text_field :last_name_kana, autofocus: true, id:"name",placeholder:"" %></td>
      </tr>

      <tr>
      <th><%= f.label :住所 %></th>
      <td><%= f.text_field :address, autofocus: true, id:"name",placeholder:"" %></td>
      </tr>

　　　<tr>
      <th><%= f.label :電話番号 %></th>
      <td><%= f.text_field :telephone_number, autofocus: true, id:"name",placeholder:"" %></td>
      </tr>

      <tr>
      <th><%= f.label :メールアドレス %></th>
      <td><%= f.text_field :email, autofocus: true, id:"name",placeholder:"" %></td>
      </tr>


    　<th><%= f.label :会員ステータス %></th>
    　<td>


      <%= f.radio_button :is_deleted, false %>
      <%= f.label :is_deleted, '有効', value: false %>

　　　<%= f.radio_button :is_deleted, true %>
      <%= f.label :is_deleted, '退会', value: true %>
     </td>
     </div>

      </tr>
     </table>


      <div><%= f.submit "変更を保存",class: "btn btn-success" %>
     <% end %>
     </div>
    </div>
    </div>

app/views/admin/users/index.html.erb
<div class="container">
   <div class="row">
    <div class style="padding: 50px;">

        <h3 class="border bg-light">会員一覧</h3>
    </div>
   </div>
 </div>

 <div class="container">
  <div class="row">
     <table class="table">
  　　　<thead>
    <tr>
       <th scope="col">プロフィール画像</th>
       <th scope="col">会員id</th>
       <th scope="col">氏名</th>
       <th scope="col">ステータス</th>
    </tr>
  </thead>
   <tbody>
     <% @users.each do |user| %>
    <tr>
     <td><%= image_tag user.image.variant(resize: '100x100'), class: 'user-image' if user.image.attached? %></td>
     <td><%= user.id %></td>
     <td><%= link_to (user.last_name + user.first_name),admin_user_path(user.id) %></td>

     <td>
       <% if user.is_deleted %>
        退会
      <% else %>
        有効
      <% end %>
     </td>
    </tr>
<% end %>
   </tbody>
   </table>
   <%#= paginate @users %>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
   <div class="row">
   <div class style="padding: 50px;">
      <h3 class="border bg-light">
        <div class="mx-3"><%= (@user.last_name + @user.first_name) %>さんの会員詳細</h3></div>

   </div>
   </div>
 </div>
 <div class="container">
   <div class="row">
       <%= image_tag @user.image.variant(resize: '100x100'), class: 'user-image' if @user.image.attached? %>
  </div>
</div>

 <div class="container">
   <div class="row">

<table class="table">
  <thead>
    <tr>
      <th>会員ID</th>
      <td><%= @user.id %></td>
    </tr>
    <tr>
     <th>氏名</th>
     <td><%= @user.last_name %> <%= @user.first_name %></td>
    </tr>
    <tr>
      <th>フリガナ</th>
      <td><%= @user.last_name_kana %> <%= @user.first_name_kana %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td>
      <%= @user.address %>
      </td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td>
      <%= @user.telephone_number %>
      </td>
    </tr>
     <tr>
      <th>メールアドレス</th>
      <td>
      <%= @user.email %>
      </td>
    </tr>
     <tr>
      <th>会員ステータス</th>
      <td>
       <% if @user.is_deleted %>
        退会
      <% else %>
        有効
      <% end %>
      </td>
    </tr>
  </thead>


</table>
 <%= link_to "編集する", edit_admin_user_path(@user.id) ,class: "btn btn-success" %>

 <!--%= link_to "注文履歴一覧を見る",admin_root_path, class: "btn btn-primary" %-->
</div>
</div>