config/routes.rb
Rails.application.routes.draw do
 
  # 顧客用
# URL /users/sign_in ...
  devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
# 管理者用
# URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords],controllers: {
  sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "public/homes#top"
  get '/about' =>'public/homes#about', as: 'about'

  namespace :admin do
    root to: "homes#top"
  end
  namespace :admin do
     resources :clothes, only: [:index, :show, :edit, :create, :update, :destroy]
    
    #get 'clothes/show'
    #get 'clothes/index'
  end

  namespace :admin do
    resources :users, only:[:index, :show, :edit, :update]


  end

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :types, only: [:create, :edit, :update, :destroy, :index]
  end
  #アドミンの
  #検索用
  #問合せ用
  namespace :admin do
    
    get 'procedures/edit'
    get 'procedures/create'
    get 'procedures/update'
  end
  
  namespace :admin do
    get 'materials/edit'
    get 'materials/create'
    get 'materials/update'
  end
  
  #namespace :public do
    #get 'procedures/post'
    #get 'procedures/create'
    #get 'procedures/edit'
  #end

  #namespace :public do
   # get 'materials/post'
    #get 'materials/create'
    #get 'materials/edit'
  #end
  namespace :public do
    resources :comments, only: [:post, :new]
    #get 'comments/post'
    #get 'comments/new'
  end
  namespace :public do
    resources :clothes, only: [:index, :show, :new, :create, :edit, :update, :destroy]
     resources :bookmarks, only: [:create, :destroy, :index]
     resources :materials, only: [:create, :destroy, :update, :post]
     resources :procedure, omly: [:create, :destroy, :update, :post]
       #collection do
        get :bookmarks
       #end
    #get 'clothes/index'
    #get 'clothes/show'
    #get 'clothes/new'
    #get 'clothes/edit'
    #get 'clothes/destroy'
  end

  namespace :public do
   resources :users, only:[:index, :show, :edit, :update]
   get 'users/list' => "uses#list"
  end

  namespace :public do
    resources :inquiries, only:[:new, :create]
  end





end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 # has_many :users, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :clothe

 validates :user_id, uniqueness: { scope: :clothe_id}
 #scopeをつけることで一つのpostに同じuserが重複してlikeできないようにする
end

app/models/clothe.rb
class Clothe < ApplicationRecord

  belongs_to :user#, through: :bookmakes
  belongs_to :genre
  belongs_to :type
  has_many :comments, dependent: :destroy  #Clothe.commentsで、投稿が所有するコメントを取得できる。
  has_many :bookmarks, dependent: :destroy
  has_many :procedures, dependent: :destroy
  has_many :materials, dependent: :destroy

  #関連付けしたモデルを一緒にデータ保存できるようにする
accepts_nested_attributes_for :procedures, :materials, allow_destroy: true



 validates :name, presence: true, length: { maximum: 255 }
 validates :short_text, presence: true, length: { maximum: 65_535 }
 validates :making_time, presence: true, length: { maximum: 30 }
 validates :point, presence: true, length: { maximum: 65_535 }

 has_one_attached :image #ここはファイル名記載


end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user  #Comment.userでコメントの所有者を取得
  belongs_to :clothe  #Comment.clotheでそのコメントがされた投稿を取得

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :clothes

end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/material.rb
class Material < ApplicationRecord
  #一対多のアソシエーション
   belongs_to :clothe
   
   validates :name, presence: true
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  
  #一対多のアソシエーション
belongs_to :clothe
has_one_attached :image #ここはファイル名記載

validates :body, presence: true
validates :image, presence: true

end

app/models/type.rb
class Type < ApplicationRecord

  has_many :clothes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :clothes, dependent: :destroy
  has_many :comments  #User.commentsで、ユーザーの所有するコメントを取得できる。
  has_many :bookmakes, dependent: :destroy
  has_many :bookmakes_clothes, through: :bookmakes, source: :clothe
  has_many :inquiries, dependent: :destroy

 has_one_attached :image #ここはファイル名記載
 #validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
 #validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
 #validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

 #validates :email, uniqueness: true
 #validates :email, presence: true
 #validates :first_name, presence: true
 #validates :last_name, presence: true

 #userオブジェクトのidとpostやlikeオブジェクトのuser_idが同じかどうかを判断
 def mine?(object)
   object.user_id == id
 end

#bookmarkes_clothesテーブルにpostオブジェクトを追加する。
#いいねを押したときに、いいねしたユーザーといいねされた投稿の情報が保存される。
 def bookmakes(post)
   bookmakes_clothes << post
 end

#bookmakes_clothesテーブルから引数のpostオブジェクトに該当するレコードを削除する。
 def unbookmark(post)
   bookmakes_colthes.destroy(post)
 end

#likes_postsテーブルに引数のpostオブジェクトに該当するレコードがあるかを判断する。
 def bookmake?(post)
   bookmakes_clothes.include?(post)
 end

 def full_name
   "#{last_name} #{first_name}"
 end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
   protected
    def after_sign_in_path_for(resource)
     if user_signed_in?
        root_path#login後遷移path要変更確認用なので
     else
       admin_root_path #login後遷移path確認用なので要変更
     end
    end

  protected

  def configure_permitted_parameters
    
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :telephone_number, :address])
  end

end

app/helpers/admin/clothes_helper.rb
module Admin::ClothesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/inquiries_helper.rb
module Admin::InquiriesHelper
end

app/helpers/admin/materials_helper.rb
module Admin::MaterialsHelper
end

app/helpers/admin/types_helper.rb
module Admin::TypesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%#= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%#= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.omniauthable? %>
  <%#- resource_class.omniauth_providers.each do |provider| %>
    <%#= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <%# end %>
<%# end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DollMother</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="shadow-sm ">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">

        <div class="container">

          <a class="navbar-brand p-1" href="/">DollMother</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">

            <ul class="navbar-nav ml-auto">

            <% if admin_signed_in? %>
            <li class="nav-item">
              <%= link_to  admin_users_path, class: 'nav-link text-white' do %>
                 会員一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  admin_clothes_path, class: 'nav-link text-white' do %>
                投稿一覧
               <% end %>
            </li>
            <li class="nav-item">
              <%#= link_to admin_root_path , class: 'nav-link text-white' do %>
                 問い合わせ
               <%# end %>
            </li>
            <li class="nav-item">
               <%= link_to admin_genres_path, class: 'nav-link text-white' do %>
                サイズ一覧
               <% end %>
            </li>
             <li class="nav-item">
               <%= link_to admin_types_path, class: 'nav-link text-white' do %>
                種類一覧
               <% end %>
            </li>
            <li class="nav-item">
               <%= link_to  destroy_admin_session_path, class: 'nav-link text-white', method: :delete do %>
                ログアウト
               <% end %>
            </li>
            <% elsif user_signed_in? %>
            <li class="nav-item">
              <%#= link_to public_user_path(current_user), class: 'nav-link text-white' do %>
               
               <%# end %>
            </li>
            <li class="nav-item">
              <%#= link_to  public_items_path, class: 'nav-link text-white' do %>
              
               <%# end %>
            </li>
            <li class="nav-item">
              <%= link_to  public_users_path, class: 'nav-link text-white' do %>
                  マイページ
               <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, class: 'nav-link text-white', method: :delete do %>
                ログアウト
               <% end %>
            </li>

            <% else %>

            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-white' do %>
                 About
               <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  public_clothes_path, class: 'nav-link text-white' do %>
                 投稿一覧
               <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  new_user_registration_path, class: 'nav-link text-white' do %>
                新規登録
               <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
                ログイン
               <% end %>

            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>


     <%= yield %>

  </body>
</html>

















<!--!DOCTYPE html>
<html>
  <head>
    <title>DollMother</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    < %= csrf_meta_tags %>
    < %= csp_meta_tag %>

    < %= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    < %= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    < %= yield %>
  </body>
</html>